In [65]:
!pip install matplotlib pandas seaborn numpy nltk

Requirement already satisfied: matplotlib in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (3.8.0)
Requirement already satisfied: pandas in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (2.1.1)
Requirement already satisfied: seaborn in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (0.13.0)
Requirement already satisfied: numpy in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (1.26.1)
Requirement already satisfied: nltk in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (3.8.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: click in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from nltk) (4.66.1)
Requirement already satisfied: six>=1.5 in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: colorama in c:\users\brin\appdata\local\r-miniconda\envs\next_app_prediction\lib\site-packages (from click->nltk) (0.4.6)

In [3]:
%matplotlib inline

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import _pickle as cPickle
import nltk

### Data preparation (same as in other notebook)

In [4]:
df = pd.read_csv('lsapp.tsv', sep='\t')
df_open = df.loc[df['event_type'] == 'Opened']

In [5]:
df_open.loc[:,'timestamp'] = pd.to_datetime(df_open['timestamp'])
df.loc[:,'timestamp'] = pd.to_datetime(df['timestamp'])

In [6]:
df

,user_id,session_id,timestamp,app_name,event_type
0,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Opened
1,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Closed
2,0,1,2018-01-16 06:01:07,Minesweeper Classic (Mines),Opened
3,0,1,2018-01-16 06:01:07,Minesweeper Classic (Mines),Closed
4,0,1,2018-01-16 06:01:08,Minesweeper Classic (Mines),Opened
...,...,...,...,...,...
3658584,291,76247,2018-04-06 14:35:15,Facebook,Closed
3658585,291,76247,2018-04-06 14:35:15,Facebook,Opened
3658586,291,76247,2018-04-06 14:35:37,Facebook,Closed
3658587,291,76247,2018-04-06 14:35:37,Facebook,Opened
3658588,291,76247,2018-04-06 14:35:52,Facebook Messenger,User Interaction

In [7]:
df['time_dff']  = df[['timestamp']].diff()
df['interaction_id'] = (((df.timestamp-df.timestamp.shift(1) > pd.Timedelta(1, 'm')) 
                              & (df.event_type == 'Opened')) 
                              | ~(df.app_name == df.app_name.shift(1))
                              | ~(df.user_id == df.user_id.shift(1))).cumsum()
df['session_id'] = (((df.timestamp-df.timestamp.shift(1) > pd.Timedelta(5, 'm')) 
                              & (df.event_type == 'Opened')) 
                              | ~(df.user_id == df.user_id.shift(1))).cumsum()
df_start = df.drop_duplicates(subset=['interaction_id'], keep='first')
df_end = df.drop_duplicates(subset=['interaction_id'], keep='last')
df_start.set_index('interaction_id', inplace=True)
df_end.set_index('interaction_id', inplace=True)
df_start.loc[:, 'open_time'] = df_start['timestamp']
df_start.loc[:, 'close_time']  = df_end['timestamp']

C:\Users\Brin\AppData\Local\Temp\ipykernel_22908\4188201099.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_start.loc[:, 'open_time'] = df_start['timestamp']
C:\Users\Brin\AppData\Local\Temp\ipykernel_22908\4188201099.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_start.loc[:, 'close_time']  = df_end['timestamp']

In [8]:
df_start

,user_id,session_id,timestamp,app_name,event_type,time_dff,open_time,close_time
interaction_id,,,,,,,,
1,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Opened,NaN,2018-01-16 06:01:05,2018-01-16 06:01:09
2,0,1,2018-01-16 06:03:44,Minesweeper Classic (Mines),Opened,0 days 00:02:35,2018-01-16 06:03:44,2018-01-16 06:04:17
3,0,1,2018-01-16 06:25:54,Gmail,User Interaction,0 days 00:21:37,2018-01-16 06:25:54,2018-01-16 06:25:54
4,0,1,2018-01-16 06:26:05,Google,Opened,0 days 00:00:11,2018-01-16 06:26:05,2018-01-16 06:26:10
5,0,1,2018-01-16 06:26:10,Instagram,Opened,0 days 00:00:00,2018-01-16 06:26:10,2018-01-16 06:26:21
...,...,...,...,...,...,...,...,...
599631,291,33218,2018-04-06 12:47:28,Facebook Messenger,Opened,0 days 00:03:29,2018-04-06 12:47:28,2018-04-06 12:53:13
599632,291,33219,2018-04-06 13:20:12,Settings,Opened,0 days 00:26:59,2018-04-06 13:20:12,2018-04-06 13:20:14
599633,291,33220,2018-04-06 14:34:15,Settings,Opened,0 days 01:14:01,2018-04-06 14:34:15,2018-04-06 14:34:17
599634,291,33220,2018-04-06 14:34:34,Facebook,Opened,0 days 00:00:17,2018-04-06 14:34:34,2018-04-06 14:35:37
599635,291,33220,2018-04-06 14:35:52,Facebook Messenger,User Interaction,0 days 00:00:15,2018-04-06 14:35:52,2018-04-06 14:35:52

## App usage records

In [9]:
len(df_start)

599635

## Sessions

In [10]:
len(df_start['session_id'].unique())

33220

## Unique apps

In [11]:
len(df_start['app_name'].unique())

87

## Users

In [12]:
len(df['user_id'].unique())

292

## Mean duration/user

In [13]:
df_start
grouped = df_start.groupby('user_id')['timestamp'].agg(['min', 'max'])

# Compute duration for each user
grouped['duration'] = grouped['max'] - grouped['min']

# Compute duration for each user in seconds
grouped['duration_seconds'] = grouped['duration'].apply(lambda x: x.total_seconds())

# Compute the mean duration
mean_duration_seconds = grouped['duration_seconds'].mean()

# Convert the mean duration back to a Timedelta object for better readability
mean_duration = pd.to_timedelta(mean_duration_seconds, unit='s')

print(mean_duration)

15 days 16:29:39.106164383

## Mean session time length

### Raw

In [14]:
df_start
grouped = df_start.groupby('session_id')

In [15]:
grouped = df_start.groupby('session_id')['timestamp'].agg(['min', 'max'])

# Compute duration for each session
grouped['duration'] = grouped['max'] - grouped['min']

# Compute duration for each user in seconds
grouped['duration_seconds'] = grouped['duration'].apply(lambda x: x.total_seconds())

# Compute the mean duration
mean_duration_seconds = grouped['duration_seconds'].mean()

# Compute the standard deviation
std_duration_seconds = grouped['duration_seconds'].std()

# Convert the mean duration back to a Timedelta object for better readability
mean_duration = pd.to_timedelta(mean_duration_seconds, unit='s')
std_duration = pd.to_timedelta(std_duration_seconds, unit='s')

print("Mean session time length:", mean_duration)
print("Standard Deviation of session time length:", std_duration)

Mean Duration: 0 days 01:16:28.070288983
Standard Deviation of Duration: 0 days 15:57:34.451853517

### Filtered

In [16]:
threshold = 2

long_sessions = grouped['duration'] > pd.Timedelta(hours=threshold)

# Compute the percentage
percentage_long_sessions = (long_sessions.sum() / len(grouped)) * 100

print(f'Percentage of sessions > {threshold}hr: ', percentage_long_sessions)

grouped = grouped[grouped['duration'] <= pd.Timedelta(hours=threshold)]

# Compute the mean duration
mean_duration_seconds = grouped['duration_seconds'].mean()

# Convert the mean duration back to a Timedelta object for better readability
mean_duration = pd.to_timedelta(mean_duration_seconds, unit='s')

print(mean_duration)

Percentage of sessions > 2hr:  10.045153521974715
0 days 00:17:43.092427132

## Median session time length

In [17]:

grouped = df_start.groupby('session_id')['timestamp'].agg(['min', 'max'])

# Compute duration for each session
grouped['duration'] = grouped['max'] - grouped['min']

# Compute duration for each user in seconds
grouped['duration_seconds'] = grouped['duration'].apply(lambda x: x.total_seconds())

# Compute the median duration
median_duration_seconds = grouped['duration_seconds'].median()

median_duration = pd.to_timedelta(median_duration_seconds, unit='s')

print("Median Duration:", median_duration)

Median Duration: 0 days 00:07:17

## Mean unique apps in each session

In [20]:
unique_apps_per_session = df_start.groupby('session_id')['app_name'].nunique()

mean_unique_apps = unique_apps_per_session.mean()
std_unique_apps = unique_apps_per_session.std()

print("Mean number of unique apps per session:", mean_unique_apps)
print("Standard Deviation of unique apps per session:", std_unique_apps)

Mean number of unique apps per session: 3.4130644190246837
Standard Deviation of unique apps per session: 2.5378790254828716

## Median unique apps in each session

In [21]:
median_unique_apps = unique_apps_per_session.median()
print("Median number of unique apps per session:", median_unique_apps)

Median number of unique apps per session: 3.0

## Mean app switches within a session

In [29]:
df_start['app_switch'] = (df_start['app_name'] != df_start['app_name'].shift()).astype(int)

session_switches = df_start.groupby('session_id')['app_switch'].sum()

mean_switches = session_switches.mean()
std_switches = session_switches.std()

print("Average (mean) of session switches:", mean_switches)
print("Standard deviation of session switches:", std_switches)

Average (mean) of session switches: 16.889283564118003
Standard deviation of session switches: 49.99798689013069

C:\Users\Brin\AppData\Local\Temp\ipykernel_22908\2587565897.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_start['app_switch'] = (df_start['app_name'] != df_start['app_name'].shift()).astype(int)

## Median app switches within a session

In [30]:
median_switches = session_switches.median()

print("Median of session switches:", median_switches)

Median of session switches: 4.0

## Session time

### Session time =  last interaction close time - first interaction open time

In [54]:
# session time as difference between first session usage open_time and last session usage close_time
sessions = df_start.groupby('session_id')

result = df_start.groupby('session_id').agg(
    min_open_time=('open_time', 'min'),
    max_close_time=('close_time', 'max')
)

# save difference as session duration
result['duration'] = result['max_close_time'] - result['min_open_time']

result
# df_session_time = df_start.groupby('session_id').apply(lambda x: x['close_time'].max() - x['open_time'].min())
# df_session_time.head(50)

                  min_open_time       max_close_time         duration
session_id
1           2018-01-16 06:01:05  2018-01-16 06:36:26  0 days 00:35:21
2           2018-01-16 07:15:56  2018-01-16 07:21:44  0 days 00:05:48
3           2018-01-16 08:02:05  2018-01-16 08:04:11  0 days 00:02:06
4           2018-01-16 08:30:44  2018-01-16 08:34:14  0 days 00:03:30
5           2018-01-16 09:45:51  2018-01-16 10:29:54  0 days 00:44:03
...                         ...                  ...              ...
33216       2018-04-06 07:14:47  2018-04-06 07:18:23  0 days 00:03:36
33217       2018-04-06 07:51:54  2018-04-06 12:24:15  0 days 04:32:21
33218       2018-04-06 12:37:57  2018-04-06 12:53:13  0 days 00:15:16
33219       2018-04-06 13:20:12  2018-04-06 13:20:14  0 days 00:00:02
33220       2018-04-06 14:34:15  2018-04-06 14:35:52  0 days 00:01:37

[33220 rows x 3 columns]

In [57]:
# Compute mean and standard deviation of session times
result['duration'] = pd.to_timedelta(result['duration'])
result['duration_seconds'] = result['duration'].dt.total_seconds()
mean_duration_seconds = result['duration_seconds'].mean()
median_duration_seconds = result['duration_seconds'].median()
std_dev_duration_seconds = result['duration_seconds'].std()

# If you want, convert the results back to Timedelta format
mean_duration = pd.to_timedelta(mean_duration_seconds, unit='s')
median_duration = pd.to_timedelta(median_duration_seconds, unit='s')
std_dev_duration = pd.to_timedelta(std_dev_duration_seconds, unit='s')
                                   
print('Mean duration: ', mean_duration)
print('Median duration: ', median_duration)
print('Standard deviation: +- ', std_dev_duration)

Mean duration:  0 days 01:21:17.673329320
Median duration:  0 days 00:10:20
Standard deviation: +-  0 days 16:01:32.896264631

## Prediction

### Setup

In [25]:
# print number of users by counting unique user ids
df_start['user_id'].nunique()

292

In [21]:
# for each user create its own dataframe
df_user = df_start.groupby('user_id')

In [24]:
# print 10 rows of first user
df_user.get_group(0).head(10)

,user_id,session_id,timestamp,app_name,event_type,time_dff,open_time,close_time
interaction_id,,,,,,,,
1,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Opened,NaN,2018-01-16 06:01:05,2018-01-16 06:01:09
2,0,1,2018-01-16 06:03:44,Minesweeper Classic (Mines),Opened,0 days 00:02:35,2018-01-16 06:03:44,2018-01-16 06:04:17
3,0,1,2018-01-16 06:25:54,Gmail,User Interaction,0 days 00:21:37,2018-01-16 06:25:54,2018-01-16 06:25:54
4,0,1,2018-01-16 06:26:05,Google,Opened,0 days 00:00:11,2018-01-16 06:26:05,2018-01-16 06:26:10
5,0,1,2018-01-16 06:26:10,Instagram,Opened,0 days 00:00:00,2018-01-16 06:26:10,2018-01-16 06:26:21
6,0,1,2018-01-16 06:26:21,Google,Opened,0 days 00:00:00,2018-01-16 06:26:21,2018-01-16 06:26:26
7,0,1,2018-01-16 06:26:26,Google Chrome,Opened,0 days 00:00:00,2018-01-16 06:26:26,2018-01-16 06:36:26
8,0,2,2018-01-16 07:15:56,Minesweeper Classic (Mines),Opened,0 days 00:39:30,2018-01-16 07:15:56,2018-01-16 07:15:58
9,0,2,2018-01-16 07:20:45,Google Chrome,Opened,0 days 00:04:47,2018-01-16 07:20:45,2018-01-16 07:20:45
10,0,2,2018-01-16 07:20:46,Minesweeper Classic (Mines),Opened,0 days 00:00:01,2018-01-16 07:20:46,2018-01-16 07:21:43

In [27]:
# for user 0 print all unique app names
df_user.get_group(0)['app_name'].unique()

array(['Minesweeper Classic (Mines)', 'Gmail', 'Google', 'Instagram',
       'Google Chrome', 'Clock', 'Maps', 'YouTube', 'Facebook',
       'Messages', 'Phone', 'Snapchat', 'Settings', 'Google Photos',
       'Hangouts', 'Amazon Shopping', 'Facebook Messenger',
       'Google Play Store', 'Calendar'], dtype=object)

### Random app

In [38]:
# create user to app dictionary including all unique app names for each user
user_to_app_dict = {}

for user_id, user_df in df_user:
    user_to_app_dict[user_id] = user_df['app_name'].unique()

# print user to app dictionary
user_to_app_dict

{0: array(['Minesweeper Classic (Mines)', 'Gmail', 'Google', 'Instagram',
        'Google Chrome', 'Clock', 'Maps', 'YouTube', 'Facebook',
        'Messages', 'Phone', 'Snapchat', 'Settings', 'Google Photos',
        'Hangouts', 'Amazon Shopping', 'Facebook Messenger',
        'Google Play Store', 'Calendar'], dtype=object),
 1: array(['Google Photos', 'Discord', 'Messages', 'Google', 'Snapchat',
        'Instagram', 'Google Chrome', 'Facebook Messenger', 'Facebook',
        'Google Drive', 'Twitter', 'Google Play Store', 'YouTube', 'Phone',
        'Spotify Music', 'Clock', 'Settings', 'Reddit'], dtype=object),
 2: array(['Android In Call UI', 'Receipt Hog', 'Gmail', 'Facebook',
        'Google Chrome', 'Instagram', 'Amazon Shopping', 'Google',
        'Snapchat', 'Maps', 'Ibotta', 'YouTube', 'Spotify Music',
        'Google Play Store', 'Settings', 'Facebook Messenger'],
       dtype=object),
 3: array(['PayPal Mobile Cash', 'Google Play Store', 'Google Chrome',
        'YouTube', 'Android In Call UI', 'Contacts', 'Samsung Notes',
        'Messaging', 'Settings', 'Gmail', 'Samsung Gallery', 'eBay',
        'Flipboard Briefing', 'Camera', 'Maps'], dtype=object),
 4: array(['Android In Call UI', 'Yahoo Mail', 'Google Chrome', 'Maps',
        'Google Play Store', 'Settings', 'Discord', 'Contacts'],
       dtype=object),
 5: array(['S’more', 'Twitter', 'Instagram', 'Google Chrome', 'Facebook',
        'YouTube', 'Snapchat', 'Gmail', 'Flipboard Briefing', 'Lucktastic',
        'Samsung Notes', 'Contacts', 'Pinterest', 'Google Play Store',
        'Settings', 'Facebook Messenger', 'Samsung Gallery', 'Messages',
        'Camera', 'Words With Friends 2', 'Google Drive',
        'Google Play Music', 'Calculator', 'Google', 'Spotify Music',
        'Samsung Internet Browser', 'Hulu', 'Discord', 'Maps',
        'Google Photos', 'Walmart', 'Calendar'], dtype=object),
 6: array(['Google', 'Snapchat', 'Samsung Internet Browser', 'Gmail',
        'Words With Friends 2', 'Reddit', 'Google Play Store', 'Maps',
        'Contacts', 'Calendar', 'Calculator', 'Google Drive',
        'PayPal Mobile Cash', 'MUIQ Survey App', 'Settings', 'Camera',
        'YouTube', 'Amazon Shopping', 'Google Chrome',
        'Facebook Messenger', 'Samsung Gallery', 'Facebook', 'Messages'],
       dtype=object),
 7: array(['Facebook Messenger', 'YouTube', 'Google', 'Google Chrome',
        'Camera', 'Messages', 'Settings', 'Google Play Store', 'Facebook',
        'Samsung Internet Browser', 'Google Play Music', 'Calendar',
        'Gmail', 'Pinterest', 'Contacts', 'Maps', 'Google Drive',
        'Snapchat', 'Google Photos', 'Samsung Gallery', 'Calculator',
        'Amazon Shopping'], dtype=object),
 8: array(['Words With Friends 2', 'WhatsApp Messenger', 'Google Chrome',
        'Google Play Store', 'Settings', 'Calendar', 'YouTube',
        'Google Play Music', 'Google', 'Phone', 'Twitter'], dtype=object),
 9: array(['Google', 'Maps', 'Gmail', 'Google Chrome', 'Samsung Gallery',
        'Calendar', 'eBay', 'Google Drive', 'Messages', 'Settings',
        'Google Play Store', 'YouTube', 'Robinhood', 'Calorie Counter',
        'Camera', 'Calculator', 'Amazon Shopping', 'Pandora Music',
        'Contacts', 'Google Photos'], dtype=object),
 10: array(['Google Play Store', 'Settings', 'Google Chrome', 'Google',
        'Microsoft Outlook', 'Maps', 'Gmail'], dtype=object),
 11: array(['Samsung Internet Browser', 'Samsung Email', 'Maps', 'Camera',
        'Contacts', 'Settings', 'Messages', 'Calculator',
        'Google Play Store', 'Google Play Music', 'Google',
        'Samsung Gallery', 'YouTube', 'Calendar', 'MUIQ Survey App',
        'Walmart', 'Google Chrome'], dtype=object),
 12: array(['Google Drive', 'Contacts', 'Messages', 'Facebook Messenger',
        'Settings', 'Instagram', 'Google Photos', 'Google', 'Gmail',
        'Facebook', 'YouTube', 'Flipboard Briefing', 'Samsung Notes',
        'Samsung Gallery', 'Camera', 'WhatsApp Messenger', 'Calendar',
        'Google Chrome', 'Google Play Store', 'Maps'], dtype=object),
 13: array(['Facebook Messenger', 'Facebook', 'Messages', 'Contacts',
        'Calculator', 'Camera', 'Samsung Gallery',
        'Samsung Internet Browser', 'Instagram', 'Yahoo Mail', 'Pinterest',
        'Amazon Shopping', 'Snapchat', 'Netflix', 'Google Chrome',
        'Walmart', 'Settings', 'Google Play Store', 'YouTube',
        'Google Photos'], dtype=object),
 14: array(['Google Chrome', 'YouTube', 'Google Play Store', 'Google',
        'Settings', 'Camera', 'Samsung Gallery', 'Contacts'], dtype=object),
 15: array(['YouTube', 'Settings', 'Google Play Store', 'Android In Call UI',
        'Microsoft Outlook', 'Gmail', 'Messenger Lite', 'Google',
        'Google Chrome', 'Messages', 'Lucktastic', 'Contacts',
        'Yahoo Mail', 'Maps', 'Reward Stash', 'Facebook', 'Google Drive',
        'OfferUp', 'Brave Browser'], dtype=object),
 16: array(['Messages', 'Slidejoy', 'Gmail', 'Twitter', 'Google Chrome',
        'Contacts', 'Camera', 'Samsung Gallery', 'Facebook Messenger',
        'Facebook', 'Google', 'Settings', 'Google Play Store',
        'Lucktastic', 'Calculator', 'Robinhood', 'Instagram', 'Maps',
        'Ibotta', 'Amazon Shopping'], dtype=object),
 17: array(['Discord', 'Messages', 'Gmail', 'Contacts', 'Facebook', 'Settings',
        'Samsung Internet Browser', 'Samsung Gallery', 'Maps',
        'Google Photos', 'Camera', 'YouTube', 'Google Play Store',
        'Google'], dtype=object),
 18: array(['Facebook', 'Yahoo Mail', 'Google Photos', 'Settings',
        'Google Chrome', 'Verizon Messages', 'Gmail', 'Instagram',
        'Google', 'Phone', 'Amazon Shopping', 'Google Play Store',
        'Facebook Messenger', 'Clock', 'Messages', 'YouTube', 'Maps',
        'MUIQ Survey App', 'Google Drive', 'Google Play Music',
        'Pinterest'], dtype=object),
 19: array(['Messages', 'Facebook', 'Gmail', 'Pinterest', 'Google Play Store',
        'Facebook Messenger', 'YouTube', 'Snapchat', 'Contacts',
        'Amazon Shopping', 'Google Chrome', 'Settings', 'Calculator',
        'Spotify Music', 'Instagram', 'Maps', 'Netflix'], dtype=object),
 20: array(['Calculator', 'Gmail', 'YouTube', 'Camera', 'Google',
        'Samsung Notes', 'Google Chrome', 'Samsung Gallery',
        'Google Play Store', 'Settings', 'Google Photos'], dtype=object),
 21: array(['Contacts', 'Settings', 'Flipboard Briefing', 'Discord', 'YouTube',
        'Samsung Email', 'Google Photos', 'Google Chrome', 'Gmail',
        'Facebook', 'Google Play Store', 'Samsung Notes', 'Google Drive',
        'Camera', 'Facebook Messenger', 'Messages', 'Maps',
        'Google Play Music', 'Calculator'], dtype=object),
 22: array(['Facebook', 'Samsung Pay', 'Google', 'Google Chrome', 'Walmart',
        'Pandora Music', 'Google Play Store', 'Contacts', 'Messages',
        'Yahoo Mail', 'Samsung Email', 'Gmail', 'Samsung Internet Browser',
        'Settings', 'Maps', 'Instagram', 'Camera', 'OfferUp',
        'Facebook Messenger', 'Snapchat', 'Lucktastic', 'YouTube',
        'Amazon Shopping', 'Spotify Music', 'Calendar', 'Calculator',
        'TextNow'], dtype=object),
 23: array(['Samsung Email', 'Messages', 'Facebook', 'Twitter',
        'Samsung Internet Browser', 'Facebook Messenger', 'Contacts',
        'Calendar', 'Google', 'Amazon Shopping', 'Google Play Store',
        'Settings', 'Google Chrome', 'eBay'], dtype=object),
 24: array(['Google Chrome', 'YouTube', 'Google', 'Google Drive', 'Calendar',
        'Google Play Store', 'Settings', 'Gmail'], dtype=object),
 25: array(['Instagram', 'Reddit', 'Google', 'Facebook Messenger',
        'Google Chrome', 'Snapchat', 'Gmail', 'Google Photos', 'eBay',
        'YouTube', 'Messages', 'Amazon Shopping', 'Clock', 'Spotify Music',
        'Twitter', 'Netflix', 'Google Play Store', 'Settings',
        'Google Drive', 'Phone', 'Ibotta', 'Walmart'], dtype=object),
 26: array(['Android In Call UI', 'YouTube', 'Contacts', 'WhatsApp Messenger',
        'Settings', 'Google Chrome', 'Maps', 'Microsoft Outlook', 'Gmail',
        'Messaging', 'Google Play Store', 'Facebook', 'Google Photos',
        'Amazon Shopping', 'Google', 'Facebook Messenger', 'Hangouts'],
       dtype=object),
 27: array(['YouTube', 'Gmail', 'Google Chrome', 'Google Play Store',
        'Google Photos', 'Phone', 'Settings', 'Google Drive', 'Discord',
        'Google'], dtype=object),
 28: array(['Facebook', 'Facebook Messenger', 'Maps', 'Google Chrome', 'Gmail',
        'WhatsApp Messenger', 'Settings', 'Google Drive', 'Google',
        'Google Photos', 'Phone', 'Clock', 'Messages', 'Google Play Store',
        'Hulu'], dtype=object),
 29: array(['Google Chrome', 'Facebook Messenger', 'Messages',
        'Messenger Lite', 'Gmail', 'Phone', 'Contacts', 'Settings',
        'Calendar', 'Google Play Store', 'Instagram'], dtype=object),
 30: array(['Google', 'Contacts', 'Samsung Gallery', 'Maps', 'Google Chrome',
        'Google Play Store', 'Settings', 'YouTube', 'Calculator', 'imo',
        'Messages', 'Snapchat', 'WhatsApp Messenger', 'Camera',
        'Swagbucks', 'Calendar'], dtype=object),
 31: array(['Telegram', 'Settings', 'Google Chrome', 'Maps', 'Google',
        'Clean Master', 'Google Play Store', 'YouTube', 'Google Drive',
        'Gmail', 'WhatsApp Messenger'], dtype=object),
 32: array(['Gmail', 'Google', 'Facebook', 'Google Chrome',
        'Google Play Store', 'Clock', 'Facebook Messenger',
        'Google Photos', 'Settings'], dtype=object),
 33: array(['Contacts', 'Messaging', 'Podcast Addict', 'Samsung Email',
        'Samsung Internet Browser', 'The PCH App', 'Robinhood',
        'Android In Call UI', 'YouTube', 'Settings', 'Google Play Store',
        'Maps', 'Samsung Gallery', 'Walmart', 'Camera', 'Calculator',
        'Google Drive'], dtype=object),
 34: array(['Facebook', 'Gmail', 'Google Drive', 'Facebook Messenger',
        'Google Chrome', 'YouTube', 'Phone', 'Android In Call UI',
        'Google Play Store', 'Settings', 'Walmart'], dtype=object),
 35: array(['Google Chrome', 'Settings', 'Gmail', 'Samsung Gallery', 'Camera',
        'Telegram', 'Google Play Store', 'Samsung Internet Browser',
        'Samsung Notes'], dtype=object),
 36: array(['Google', 'Discord', 'YouTube', 'Google Chrome', 'Facebook',
        'Instagram', 'Phone', 'Maps', 'Clock', 'Facebook Messenger',
        'Google Play Store', 'Settings', 'Spotify Music', 'Gmail',
        'Amazon Shopping', 'Google Photos', 'PayPal Mobile Cash'],
       dtype=object),
 37: array(['Phone', 'Facebook', 'Clock', 'Settings', 'Reddit', 'Gmail',
        'YouTube', 'Google Chrome', 'Google', 'Facebook Messenger',
        'Google Play Store', 'Google Photos', 'Verizon Messages',
        'Calendar', 'Walmart', 'Google Play Music', 'Google Drive'],
       dtype=object),
 38: array(['Yahoo Mail', 'Google Chrome', 'Phone', 'Hangouts', 'Gmail',
        'Google', 'Amazon Shopping', 'Messages', 'Facebook Messenger',
        'Settings', 'Google Play Store', 'Clock', 'eBay', 'Google Drive'],
       dtype=object),
 39: array(['Facebook', 'Facebook Messenger', 'Google', 'Gmail', 'Maps',
        'Settings', 'Google Chrome', 'Quora', 'Snapchat',
        'Google Play Store', 'Phone', 'Instagram', 'Google Drive',
        'Twitter', 'Amazon Shopping', 'YouTube', 'Google Photos',
        'Pandora Music', 'Messages'], dtype=object),
 40: array(['Facebook Messenger', 'Facebook', 'Twitter', 'Microsoft Outlook',
        'Google Chrome', 'Amazon Shopping', 'Google Play Store',
        'Words With Friends 2', 'Messaging', 'Google', 'Calorie Counter',
        'Android In Call UI', 'Contacts', 'Instagram', 'Spotify Music',
        'Settings'], dtype=object),
 41: array(['Google Chrome', 'Spotify Music', 'Contacts', 'YouTube',
        'Yahoo Mail', 'Samsung Gallery', 'Messages', 'Settings',
        'Calculator', 'Calendar', 'Facebook', 'Google Play Store',
        'Facebook Messenger', 'Samsung Internet Browser', 'Camera'],
       dtype=object),
 42: array(['Reddit', 'Google', 'Google Play Store', 'Settings',
        'Google Chrome', 'Messaging', 'Camera', 'Samsung Gallery',
        'Snapchat', 'Maps', 'Samsung Internet Browser'], dtype=object),
 43: array(['Messages', 'Google', 'Pinterest', 'Google Chrome',
        'Google Play Store', 'Pandora Music', 'Microsoft Outlook',
        'Settings', 'Instagram', 'Camera', 'Snapchat', 'Maps', 'Facebook',
        'Twitter', 'Samsung Gallery', 'YouTube'], dtype=object),
 44: array(['Google Chrome', 'Google Play Store', 'Settings',
        'Verizon Messages', 'Calculator', 'Calendar', 'Reddit', 'Gmail',
        'Netflix', 'Instagram', 'Maps', 'Camera', 'Samsung Gallery',
        'Robinhood', 'YouTube', 'Contacts', 'Google'], dtype=object),
 45: array(['Calendar', 'Gmail', 'Maps', 'Snapchat', 'Google', 'Reddit',
        'Google Photos', 'Google Play Store', 'Settings', 'Google Drive',
        'YouTube', 'Discord', 'Contacts'], dtype=object),
 46: array(['Facebook', 'WhatsApp Messenger', 'Messaging', 'Google Chrome',
        'Contacts', 'Android In Call UI', 'Gmail', 'Google',
        'Flipboard Briefing', 'Samsung Email', 'Camera',
        'Facebook Messenger', 'Telegram', 'YouTube', 'Samsung Gallery',
        'Twitter', 'Hangouts', 'Instagram', 'Samsung Notes', 'Settings',
        'Calculator', 'Google Play Store'], dtype=object),
 47: array(['Settings', 'Contacts', 'Android In Call UI', 'Google Play Store',
        'Google Drive', 'Gmail', 'Messaging', 'Google Chrome',
        'Google Photos', 'Facebook Messenger', 'Facebook', 'Google',
        'YouTube', 'Spotify Music'], dtype=object),
 48: array(['Instagram', 'Twitter', 'Google Chrome', 'Gmail', 'Telegram',
        'Messaging', 'WhatsApp Messenger', 'Google', 'YouTube', 'Maps',
        'Contacts', 'imo', 'Android In Call UI', 'Phone',
        'Google Play Store', 'Settings'], dtype=object),
 49: array(['Messages', 'Samsung Pay', 'Contacts', 'Google Chrome', 'Gmail',
        'Instagram', 'Calendar', 'Settings', 'Google',
        'Samsung Internet Browser', 'Facebook', 'Google Play Store',
        'Samsung Gallery', 'Spotify Music', 'Calculator', 'Google Drive'],
       dtype=object),
 50: array(['Samsung Internet Browser', 'Reward Stash', 'Calculator',
        'Settings', 'Maps', 'Camera', 'Samsung Gallery', 'Movie Play Box',
        'Google Play Store', 'Contacts', 'Google Chrome', 'YouTube',
        'Messaging', 'Pandora Music', 'Walmart', 'Facebook Messenger',
        'Google', 'Swagbucks', 'Google Drive', 'MUIQ Survey App',
        'Google Photos'], dtype=object),
 51: array(['Google', 'YouTube', 'Maps', 'Google Chrome', 'Google Play Store',
        'Settings', 'Google Play Music'], dtype=object),
 52: array(['Discord', 'Google Chrome', 'Facebook', 'Google', 'Camera',
        'Gmail', 'Facebook Messenger', 'Samsung Gallery', 'Twitter',
        'Contacts', 'Google Play Store', 'Settings', 'YouTube', 'Calendar',
        'Messages'], dtype=object),
 53: array(['Google Play Store', 'Google Chrome', 'Google', 'Google Photos',
        'Settings', 'Gmail'], dtype=object),
 54: array(['Facebook', 'Messaging', 'Google Chrome', 'Contacts',
        'Android In Call UI', 'Hangouts', 'Amazon Shopping', 'Walmart',
        'Pandora Music', 'Words With Friends 2', 'Twitter', 'Maps',
        'Google', 'Gmail', 'YouTube', 'Google Play Store', 'Settings',
        'Facebook Messenger', 'Google Drive', 'Calendar', 'Google Photos',
        'Snapchat', 'Google Play Music'], dtype=object),
 55: array(['Google', 'Samsung Internet Browser', 'Contacts', 'Gmail',
        'Ibotta', 'Microsoft Outlook', 'Samsung Pay', 'Messages',
        'Facebook', 'Google Play Music', 'Snapchat', 'Camera',
        'Samsung Gallery', 'Google Drive', 'Google Chrome',
        'Facebook Messenger', 'Settings', 'Pinterest', 'Google Play Store',
        'YouTube', 'eBay', 'PayPal Mobile Cash', 'Walmart', 'Maps'],
       dtype=object),
 56: array(['Google Chrome', 'Google', 'Gmail', 'Google Play Store',
        'Settings', 'Maps'], dtype=object),
 57: array(['Yahoo Mail', 'Google', 'Google Chrome', 'Samsung Email',
        'Contacts', 'Messages', 'Microsoft Bing Search', 'YouTube',
        'Google Play Store', 'Maps', 'Flipboard Briefing',
        'WhatsApp Messenger', 'Settings'], dtype=object),
 58: array(['S’more', 'Slidejoy', 'Google', 'Google Chrome',
        'Google Play Store', 'YouTube', 'Facebook', 'Facebook Messenger',
        'Reddit', 'Settings', 'Google Photos', 'Gmail', 'Google Drive',
        'Contacts', 'Podcast Addict', 'Phone'], dtype=object),
 59: array(['Instagram', 'Samsung Email', 'Facebook', 'Google Play Store',
        'Google', 'Verizon Messages', 'Samsung Pay', 'Google Chrome',
        'Contacts', 'Facebook Messenger', 'Camera', 'Calculator',
        'YouTube', 'Calorie Counter', 'Ibotta', 'Twitter', 'Settings'],
       dtype=object),
 60: array(['Google Play Store', 'Facebook', 'Google Chrome', 'Gmail',
        'Settings', 'Hangouts', 'Google', 'Robinhood', 'eBay', 'YouTube',
        'Twitter', 'Clean Master', 'Receipt Hog', 'Facebook Messenger',
        'MUIQ Survey App', 'Walmart', 'Contacts', 'Messaging',
        'Google Drive', 'Android In Call UI'], dtype=object),
 61: array(['Facebook Messenger', 'YouTube', 'Google Play Store', 'Google',
        'Android In Call UI', 'SurveyCow', 'Facebook', 'Yahoo Mail',
        'Google Chrome', 'Pandora Music', 'Settings', 'Camera',
        'Samsung Gallery', 'Maps', 'Contacts', 'Swagbucks',
        'Google Photos', 'MUIQ Survey App', 'Calculator', 'Messaging',
        'Receipt Hog', 'Ibotta'], dtype=object),
 62: array(['Google', 'YouTube', 'Google Chrome', 'Yahoo Mail', 'Gmail',
        'Google Play Store', 'Maps', 'Settings', 'Messages',
        'Microsoft Bing Search'], dtype=object),
 63: array(['Facebook', 'Facebook Messenger', 'Google Play Store', 'Contacts',
        'Android In Call UI', 'Messaging', 'Maps', 'Google', 'Snapchat',
        'Settings', 'Google Play Music', 'Pinterest',
        'Samsung Internet Browser', 'Calendar', 'Gmail', 'Google Photos'],
       dtype=object),
 64: array(['Google Play Store', 'Google Chrome', 'Maps', 'Facebook',
        'Messages', 'Reddit', 'Camera', 'Contacts', 'Samsung Gallery',
        'Google Drive', 'Samsung Email', 'Walmart', 'Ibotta', 'Quora',
        'Facebook Messenger', 'Settings', 'Calendar', 'Gmail',
        'Calculator', 'Lucktastic', 'YouTube', 'Google Photos',
        'Receipt Hog'], dtype=object),
 65: array(['Hulu', 'Google Play Store'], dtype=object),
 66: array(['Instagram', 'Google Chrome', 'Gmail', 'Telegram',
        'Google Play Store', 'WhatsApp Messenger', 'Spotify Music',
        'Settings', 'Google Drive', 'YouTube', 'Facebook Messenger',
        'Google', 'Maps'], dtype=object),
 67: array(['Facebook Messenger', 'Discord', 'YouTube', 'Google Chrome',
        'Google', 'Settings', 'Phone', 'Instagram', 'Netflix', 'Gmail',
        'Facebook', 'Calendar', 'Snapchat', 'Messages',
        'Google Play Store', 'Amazon Shopping', 'Google Photos',
        'MUIQ Survey App', 'Reddit', 'PayPal Mobile Cash', 'Maps',
        'Spotify Music', 'Hulu', 'Google Drive', 'Clock', 'Baseball Boy!'],
       dtype=object),
 68: array(['Google Chrome', 'Amazon Shopping', 'Google Play Store', 'Google',
        'Receipt Hog', 'Instagram', 'Facebook', 'Clock', 'Snapchat',
        'Swagbucks', 'Gmail', 'Facebook Messenger', 'YouTube', 'Maps',
        'Messages', 'Swagbucks Watch (TV)', 'Settings', 'Pinterest',
        'Yahoo Mail', 'Microsoft Outlook', 'Phone', 'WhatsApp Messenger',
        'Google Photos', 'Google Drive', 'Calendar'], dtype=object),
 69: array(['Messages', 'YouTube', 'Google Photos', 'OfferUp', 'Contacts',
        'Settings', 'Reddit', 'Google Play Store', 'Maps', 'Google Chrome',
        'Camera', 'Samsung Gallery', 'Gmail', 'Google',
        'Microsoft Outlook', 'Amazon Shopping', 'Google Play Music'],
       dtype=object),
 70: array(['Messaging', 'Contacts', 'Android In Call UI', 'Instagram',

In [40]:
# iterate through all df_start interactions and choose app_name as random app from user_to_app_dict for user_id
df_start['random_app_name'] = df_start.apply(lambda row: np.random.choice(user_to_app_dict[row['user_id']]), axis=1)
df_start.head(100)

C:\Users\Brin\AppData\Local\Temp\ipykernel_17340\1922601193.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_start['random_app_name'] = df_start.apply(lambda row: np.random.choice(user_to_app_dict[row['user_id']]), axis=1)

,user_id,session_id,timestamp,app_name,event_type,time_dff,open_time,close_time,random_app_name
interaction_id,,,,,,,,,
1,0,1,2018-01-16 06:01:05,Minesweeper Classic (Mines),Opened,NaN,2018-01-16 06:01:05,2018-01-16 06:01:09,Google Play Store
2,0,1,2018-01-16 06:03:44,Minesweeper Classic (Mines),Opened,0 days 00:02:35,2018-01-16 06:03:44,2018-01-16 06:04:17,Google Play Store
3,0,1,2018-01-16 06:25:54,Gmail,User Interaction,0 days 00:21:37,2018-01-16 06:25:54,2018-01-16 06:25:54,Calendar
4,0,1,2018-01-16 06:26:05,Google,Opened,0 days 00:00:11,2018-01-16 06:26:05,2018-01-16 06:26:10,Amazon Shopping
5,0,1,2018-01-16 06:26:10,Instagram,Opened,0 days 00:00:00,2018-01-16 06:26:10,2018-01-16 06:26:21,Google Chrome
...,...,...,...,...,...,...,...,...,...
96,0,23,2018-01-16 22:32:56,Gmail,Closed,0 days 00:00:01,2018-01-16 22:32:56,2018-01-16 22:32:56,Google
97,0,23,2018-01-16 22:32:57,Phone,Opened,0 days 00:00:01,2018-01-16 22:32:57,2018-01-16 22:34:07,Hangouts
98,0,23,2018-01-16 22:34:07,Gmail,Opened,0 days 00:00:00,2018-01-16 22:34:07,2018-01-16 22:34:47,Amazon Shopping
99,0,23,2018-01-16 22:34:47,Google,Opened,0 days 00:00:00,2018-01-16 22:34:47,2018-01-16 22:35:22,Facebook Messenger
100,0,23,2018-01-16 22:35:22,Google Chrome,Opened,0 days 00:00:00,2018-01-16 22:35:22,2018-01-16 22:39:59,Messages

In [43]:
# create dicitonary user to accuracy
user_to_accuracy_dict = {}

# go through all interactions and check if app_name is in random_app_name for each user and save accuracy
for user_id, user_df in df_user:
    # iterate through all interactions for user_id
    accuracy = 0

    for index, row in user_df.iterrows():
        if row['app_name'] == row['random_app_name']:
            accuracy += 1

    user_to_accuracy_dict[user_id] = accuracy / len(user_df)

# print user to accuracy dictionary
user_to_accuracy_dict

{0: 0.060836501901140684,
 1: 0.06334841628959276,
 2: 0.06521739130434782,
 3: 0.08284023668639054,
 4: 0.13157894736842105,
 5: 0.03174045443897868,
 6: 0.04729082902546429,
 7: 0.043726235741444866,
 8: 0.13333333333333333,
 9: 0.046118721461187215,
 10: 0.125,
 11: 0.06609442060085836,
 12: 0.03162055335968379,
 13: 0.05153203342618384,
 14: 0.1702127659574468,
 15: 0.06201550387596899,
 16: 0.04830917874396135,
 17: 0.10493827160493827,
 18: 0.04808767613509282,
 19: 0.07471264367816093,
 20: 0.10975609756097561,
 21: 0.06164383561643835,
 22: 0.03260869565217391,
 23: 0.07058823529411765,
 24: 0.1717171717171717,
 25: 0.05437597099948213,
 26: 0.06127966356263142,
 27: 0.11194029850746269,
 28: 0.055299539170506916,
 29: 0.0914396887159533,
 30: 0.08053691275167785,
 31: 0.08647575843493054,
 32: 0.14942528735632185,
 33: 0.05409643277146217,
 34: 0.07954545454545454,
 35: 0.14285714285714285,
 36: 0.06561859193438141,
 37: 0.06218487394957983,
 38: 0.06769596199524941,
 39: 0.04265997490589712,
 40: 0.059964726631393295,
 41: 0.07228915662650602,
 42: 0.09523809523809523,
 43: 0.05975103734439834,
 44: 0.047080979284369114,
 45: 0.0959409594095941,
 46: 0.031746031746031744,
 47: 0.08450704225352113,
 48: 0.06690140845070422,
 49: 0.06237816764132553,
 50: 0.042837792075855065,
 51: 0.13513513513513514,
 52: 0.05785123966942149,
 53: 0.22727272727272727,
 54: 0.03969754253308128,
 55: 0.034013605442176874,
 56: 0.16049382716049382,
 57: 0.06694560669456066,
 58: 0.05822784810126582,
 59: 0.05196629213483146,
 60: 0.0595903165735568,
 61: 0.042380888109056554,
 62: 0.0881057268722467,
 63: 0.04892966360856269,
 64: 0.04256854256854257,
 65: 1.0,
 66: 0.06741573033707865,
 67: 0.04049416609471517,
 68: 0.0437729454956227,
 69: 0.05286343612334802,
 70: 0.10810810810810811,
 71: 0.041895784236711184,
 72: 0.06666666666666667,
 73: 0.061243144424131625,
 74: 0.03919663103336573,
 75: 0.03287671232876712,
 76: 0.0975609756097561,
 77: 0.10218978102189781,
 78: 0.08083832335329341,
 79: 0.04644194756554307,
 80: 0.07365792759051186,
 81: 0.09734513274336283,
 82: 0.061872909698996656,
 83: 0.05779334500875657,
 84: 0.06484641638225255,
 85: 0.049019607843137254,
 86: 0.18518518518518517,
 87: 0.04838709677419355,
 88: 0.07142857142857142,
 89: 0.04918032786885246,
 90: 0.08,
 91: 0.04242424242424243,
 92: 0.061224489795918366,
 93: 0.044186046511627906,
 94: 0.05678670360110803,
 95: 0.09090909090909091,
 96: 0.09420289855072464,
 97: 0.1111111111111111,
 98: 0.25,
 99: 0.05049088359046283,
 100: 0.0,
 101: 0.09259259259259259,
 102: 0.048507462686567165,
 103: 0.0787037037037037,
 104: 0.06028577020943433,
 105: 0.05764411027568922,
 106: 0.08252947481243302,
 107: 0.05708460754332314,
 108: 0.054039448797622264,
 109: 0.07667731629392971,
 110: 0.14893617021276595,
 111: 0.059805285118219746,
 112: 0.03406865568482894,
 113: 0.08333333333333333,
 114: 0.06357388316151202,
 115: 0.034693269803454434,
 116: 0.04282095931613107,
 117: 0.2857142857142857,
 118: 0.0440251572327044,
 119: 0.03764779091474798,
 120: 0.078125,
 121: 0.021406727828746176,
 122: 0.0872093023255814,
 123: 0.05555555555555555,
 124: 0.060191518467852256,
 125: 0.042042042042042045,
 126: 0.014285714285714285,
 127: 0.07086614173228346,
 128: 0.046289493019838354,
 129: 0.05479984453944812,
 130: 0.05813953488372093,
 131: 0.03948025987006497,
 132: 0.045454545454545456,
 133: 0.048038049940546966,
 134: 0.25,
 135: 0.038746908491343775,
 136: 0.05931612002791347,
 137: 0.03850440209517441,
 138: 0.03525798124366892,
 139: 0.07652210175145956,
 140: 0.05508130081300813,
 141: 0.0641025641025641,
 142: 0.0364963503649635,
 143: 0.08058608058608059,
 144: 0.04477611940298507,
 145: 0.09206349206349207,
 146: 0.043010752688172046,
 147: 0.03102878716375649,
 148: 0.05694915254237288,
 149: 0.041121495327102804,
 150: 0.05685856432125089,
 151: 0.04481675392670157,
 152: 0.06923076923076923,
 153: 0.09137055837563451,
 154: 0.04058901264866906,
 155: 0.10050251256281408,
 156: 0.0967741935483871,
 157: 0.25,
 158: 0.042242703533026116,
 159: 0.06451612903225806,
 160: 0.045741723527925195,
 161: 0.03929273084479371,
 162: 0.04284471509351892,
 163: 0.0599250936329588,
 164: 0.061946902654867256,
 165: 0.07215189873417721,
 166: 0.26865671641791045,
 167: 0.13953488372093023,
 168: 0.04498269896193772,
 169: 0.13175675675675674,
 170: 0.6,
 171: 1.0,
 172: 0.06443298969072164,
 173: 0.057754010695187166,
 174: 0.029914529914529916,
 175: 0.04216867469879518,
 176: 0.03347280334728033,
 177: 1.0,
 178: 0.06633906633906633,
 179: 0.03886138613861386,
 180: 0.03727144866385373,
 181: 0.13,
 182: 0.13385826771653545,
 183: 0.053742802303262956,
 184: 0.12903225806451613,
 185: 0.05223880597014925,
 186: 0.0574468085106383,
 187: 0.039342337052260715,
 188: 0.06543494996150885,
 189: 0.0456989247311828,
 190: 0.10283687943262411,
 191: 0.047619047619047616,
 192: 0.033183616008580816,
 193: 0.09090909090909091,
 194: 0.07553956834532374,
 195: 0.06338028169014084,
 196: 0.04854831032841504,
 197: 0.04430379746835443,
 198: 0.054161688570290724,
 199: 0.23684210526315788,
 200: 0.0546448087431694,
 201: 0.04285714285714286,
 202: 0.05627009646302251,
 203: 0.04756596060943887,
 204: 0.04085987924214033,
 205: 0.03616236162361624,
 206: 0.05255878284923928,
 207: 0.057007125890736345,
 208: 0.07446808510638298,
 209: 0.087248322147651,
 210: 0.1935483870967742,
 211: 0.0451693851944793,
 212: 0.03499469777306469,
 213: 0.06842105263157895,
 214: 0.04361370716510903,
 215: 0.06197854588796186,
 216: 0.0684931506849315,
 217: 0.058823529411764705,
 218: 0.0859375,
 219: 0.04950495049504951,
 220: 0.08695652173913043,
 221: 0.052288911495422176,
 222: 0.14049586776859505,
 223: 0.0,
 224: 0.06666666666666667,
 225: 0.0413625304136253,
 226: 0.05160807778608826,
 227: 0.05132796180244703,
 228: 0.2727272727272727,
 229: 0.037155963302752296,
 230: 0.1746031746031746,
 231: 0.04986642920747997,
 232: 1.0,
 233: 0.06481481481481481,
 234: 0.1111111111111111,
 235: 0.09090909090909091,
 236: 0.1111111111111111,
 237: 0.05405405405405406,
 238: 0.039603960396039604,
 239: 0.05531914893617021,
 240: 0.1406926406926407,
 241: 0.0654627539503386,
 242: 0.06745182012847965,
 243: 1.0,
 244: 0.058774834437086095,
 245: 0.07746478873239436,
 246: 0.05044843049327354,
 247: 0.04984740590030519,
 248: 0.04738154613466334,
 249: 0.06378132118451026,
 250: 1.0,
 251: 0.05072103431128792,
 252: 0.047253634894991924,
 253: 0.07751937984496124,
 254: 0.03770692826486818,
 255: 0.057880230518667,
 256: 0.18181818181818182,
 257: 0.04813664596273292,
 258: 0.05263157894736842,
 259: 0.03984575835475578,
 260: 0.04186834462729913,
 261: 0.058823529411764705,
 262: 0.05256183745583039,
 263: 0.05121470781352593,
 264: 0.06184935701163503,
 265: 0.06111111111111111,
 266: 0.05025125628140704,
 267: 0.03420682377769961,
 268: 0.183206106870229,
 269: 0.04973002404827805,
 270: 0.04349634353446782,
 271: 0.0330188679245283,
 272: 0.10344827586206896,
 273: 0.038898233809924306,
 274: 0.05263157894736842,
 275: 0.0636604774535809,
 276: 0.07932692307692307,
 277: 0.05411255411255411,
 278: 0.10204081632653061,
 279: 0.058922558922558925,
 280: 0.06515151515151515,
 281: 0.08129175946547884,
 282: 0.06882591093117409,
 283: 0.050401753104455806,
 284: 0.04227405247813411,
 285: 0.04467871485943775,
 286: 0.08333333333333333,
 287: 0.04452054794520548,
 288: 1.0,
 289: 0.04721311475409836,
 290: 0.03808684976112312,
 291: 0.0657439446366782}

#### Results

In [44]:
# Calculate mean and standard deviation of accuracy
mean_accuracy = np.mean(list(user_to_accuracy_dict.values()))
std_accuracy = np.std(list(user_to_accuracy_dict.values()))

mean_accuracy, std_accuracy

(0.09545466117908077, 0.15162234054750554)

### Most popular app

In [48]:
# create user most popular app dictionary
user_to_most_popular_app_dict = {}

# for each user iterate through all interactions and count app_name occurences
for user_id, user_df in df_user:
    # iterate through all interactions for user_id
    app_name_to_count_dict = {}

    for index, row in user_df.iterrows():
        if row['app_name'] in app_name_to_count_dict:
            app_name_to_count_dict[row['app_name']] += 1
        else:
            app_name_to_count_dict[row['app_name']] = 1

    print('user_id: ', user_id)
    print('app_name_to_count_dict: ', app_name_to_count_dict)
    # find most popular app_name for user_id
    most_popular_app_name = max(app_name_to_count_dict, key=app_name_to_count_dict.get)
    user_to_most_popular_app_dict[user_id] = most_popular_app_name

# print user to most popular app dictionary
user_to_most_popular_app_dict

user_id:  0
app_name_to_count_dict:  {'Minesweeper Classic (Mines)': 174, 'Gmail': 50, 'Google': 170, 'Instagram': 21, 'Google Chrome': 117, 'Clock': 57, 'Maps': 39, 'YouTube': 3, 'Facebook': 20, 'Messages': 70, 'Phone': 35, 'Snapchat': 2, 'Settings': 6, 'Google Photos': 4, 'Hangouts': 1, 'Amazon Shopping': 3, 'Facebook Messenger': 9, 'Google Play Store': 7, 'Calendar': 1}
user_id:  1
app_name_to_count_dict:  {'Google Photos': 4, 'Discord': 80, 'Messages': 15, 'Google': 84, 'Snapchat': 55, 'Instagram': 19, 'Google Chrome': 46, 'Facebook Messenger': 34, 'Facebook': 18, 'Google Drive': 1, 'Twitter': 13, 'Google Play Store': 8, 'YouTube': 6, 'Phone': 9, 'Spotify Music': 35, 'Clock': 2, 'Settings': 2, 'Reddit': 11}
user_id:  2
app_name_to_count_dict:  {'Android In Call UI': 12, 'Receipt Hog': 6, 'Gmail': 62, 'Facebook': 16, 'Google Chrome': 73, 'Instagram': 15, 'Amazon Shopping': 6, 'Google': 6, 'Snapchat': 9, 'Maps': 4, 'Ibotta': 2, 'YouTube': 1, 'Spotify Music': 2, 'Google Play Store': 5, 'Settings': 8, 'Facebook Messenger': 3}
user_id:  3
app_name_to_count_dict:  {'PayPal Mobile Cash': 2, 'Google Play Store': 4, 'Google Chrome': 68, 'YouTube': 6, 'Android In Call UI': 10, 'Contacts': 11, 'Samsung Notes': 2, 'Messaging': 27, 'Settings': 2, 'Gmail': 1, 'Samsung Gallery': 15, 'eBay': 14, 'Flipboard Briefing': 1, 'Camera': 1, 'Maps': 5}
user_id:  4
app_name_to_count_dict:  {'Android In Call UI': 21, 'Yahoo Mail': 31, 'Google Chrome': 41, 'Maps': 9, 'Google Play Store': 22, 'Settings': 6, 'Discord': 18, 'Contacts': 4}
user_id:  5
app_name_to_count_dict:  {'S’more': 1310, 'Twitter': 2875, 'Instagram': 344, 'Google Chrome': 898, 'Facebook': 175, 'YouTube': 610, 'Snapchat': 556, 'Gmail': 331, 'Flipboard Briefing': 15, 'Lucktastic': 73, 'Samsung Notes': 107, 'Contacts': 35, 'Pinterest': 48, 'Google Play Store': 81, 'Settings': 80, 'Facebook Messenger': 10, 'Samsung Gallery': 45, 'Messages': 298, 'Camera': 53, 'Words With Friends 2': 3, 'Google Drive': 9, 'Google Play Music': 32, 'Calculator': 6, 'Google': 27, 'Spotify Music': 302, 'Samsung Internet Browser': 3, 'Hulu': 132, 'Discord': 2, 'Maps': 65, 'Google Photos': 6, 'Walmart': 6, 'Calendar': 1}
user_id:  6
app_name_to_count_dict:  {'Google': 188, 'Snapchat': 867, 'Samsung Internet Browser': 588, 'Gmail': 606, 'Words With Friends 2': 68, 'Reddit': 1291, 'Google Play Store': 102, 'Maps': 30, 'Contacts': 25, 'Calendar': 22, 'Calculator': 262, 'Google Drive': 65, 'PayPal Mobile Cash': 91, 'MUIQ Survey App': 14, 'Settings': 51, 'Camera': 43, 'YouTube': 145, 'Amazon Shopping': 56, 'Google Chrome': 153, 'Facebook Messenger': 208, 'Samsung Gallery': 45, 'Facebook': 274, 'Messages': 29}
user_id:  7
app_name_to_count_dict:  {'Facebook Messenger': 54, 'YouTube': 40, 'Google': 247, 'Google Chrome': 225, 'Camera': 1, 'Messages': 55, 'Settings': 85, 'Google Play Store': 68, 'Facebook': 38, 'Samsung Internet Browser': 84, 'Google Play Music': 10, 'Calendar': 4, 'Gmail': 45, 'Pinterest': 2, 'Contacts': 9, 'Maps': 5, 'Google Drive': 51, 'Snapchat': 11, 'Google Photos': 6, 'Samsung Gallery': 9, 'Calculator': 1, 'Amazon Shopping': 2}
user_id:  8
app_name_to_count_dict:  {'Words With Friends 2': 11, 'WhatsApp Messenger': 3, 'Google Chrome': 4, 'Google Play Store': 1, 'Settings': 1, 'Calendar': 1, 'YouTube': 2, 'Google Play Music': 2, 'Google': 3, 'Phone': 1, 'Twitter': 1}
user_id:  9
app_name_to_count_dict:  {'Google': 441, 'Maps': 34, 'Gmail': 229, 'Google Chrome': 694, 'Samsung Gallery': 30, 'Calendar': 19, 'eBay': 33, 'Google Drive': 41, 'Messages': 237, 'Settings': 23, 'Google Play Store': 46, 'YouTube': 21, 'Robinhood': 270, 'Calorie Counter': 1, 'Camera': 8, 'Calculator': 5, 'Amazon Shopping': 26, 'Pandora Music': 5, 'Contacts': 26, 'Google Photos': 1}
user_id:  10
app_name_to_count_dict:  {'Google Play Store': 10, 'Settings': 43, 'Google Chrome': 64, 'Google': 32, 'Microsoft Outlook': 1, 'Maps': 1, 'Gmail': 1}
user_id:  11
app_name_to_count_dict:  {'Samsung Internet Browser': 1169, 'Samsung Email': 783, 'Maps': 54, 'Camera': 149, 'Contacts': 140, 'Settings': 137, 'Messages': 311, 'Calculator': 24, 'Google Play Store': 221, 'Google Play Music': 6, 'Google': 25, 'Samsung Gallery': 171, 'YouTube': 27, 'Calendar': 29, 'MUIQ Survey App': 142, 'Walmart': 104, 'Google Chrome': 3}
user_id:  12
app_name_to_count_dict:  {'Google Drive': 13, 'Contacts': 6, 'Messages': 14, 'Facebook Messenger': 37, 'Settings': 9, 'Instagram': 55, 'Google Photos': 12, 'Google': 24, 'Gmail': 27, 'Facebook': 53, 'YouTube': 61, 'Flipboard Briefing': 5, 'Samsung Notes': 54, 'Samsung Gallery': 20, 'Camera': 15, 'WhatsApp Messenger': 76, 'Calendar': 5, 'Google Chrome': 14, 'Google Play Store': 4, 'Maps': 2}
user_id:  13
app_name_to_count_dict:  {'Facebook Messenger': 39, 'Facebook': 175, 'Messages': 77, 'Contacts': 7, 'Calculator': 10, 'Camera': 19, 'Samsung Gallery': 21, 'Samsung Internet Browser': 156, 'Instagram': 35, 'Yahoo Mail': 92, 'Pinterest': 27, 'Amazon Shopping': 5, 'Snapchat': 24, 'Netflix': 7, 'Google Chrome': 1, 'Walmart': 3, 'Settings': 3, 'Google Play Store': 15, 'YouTube': 1, 'Google Photos': 1}
user_id:  14
app_name_to_count_dict:  {'Google Chrome': 23, 'YouTube': 7, 'Google Play Store': 6, 'Google': 3, 'Settings': 2, 'Camera': 2, 'Samsung Gallery': 1, 'Contacts': 3}
user_id:  15
app_name_to_count_dict:  {'YouTube': 82, 'Settings': 28, 'Google Play Store': 52, 'Android In Call UI': 40, 'Microsoft Outlook': 55, 'Gmail': 145, 'Messenger Lite': 54, 'Google': 55, 'Google Chrome': 56, 'Messages': 93, 'Lucktastic': 8, 'Contacts': 26, 'Yahoo Mail': 16, 'Maps': 14, 'Reward Stash': 5, 'Facebook': 25, 'Google Drive': 7, 'OfferUp': 7, 'Brave Browser': 6}
user_id:  16
app_name_to_count_dict:  {'Messages': 78, 'Slidejoy': 273, 'Gmail': 57, 'Twitter': 36, 'Google Chrome': 221, 'Contacts': 23, 'Camera': 7, 'Samsung Gallery': 6, 'Facebook Messenger': 46, 'Facebook': 20, 'Google': 9, 'Settings': 5, 'Google Play Store': 26, 'Lucktastic': 3, 'Calculator': 5, 'Robinhood': 1, 'Instagram': 2, 'Maps': 8, 'Ibotta': 1, 'Amazon Shopping': 1}
user_id:  17
app_name_to_count_dict:  {'Discord': 47, 'Messages': 45, 'Gmail': 5, 'Contacts': 3, 'Facebook': 6, 'Settings': 3, 'Samsung Internet Browser': 16, 'Samsung Gallery': 10, 'Maps': 3, 'Google Photos': 2, 'Camera': 6, 'YouTube': 14, 'Google Play Store': 1, 'Google': 1}
user_id:  18
app_name_to_count_dict:  {'Facebook': 513, 'Yahoo Mail': 389, 'Google Photos': 94, 'Settings': 31, 'Google Chrome': 1125, 'Verizon Messages': 420, 'Gmail': 126, 'Instagram': 6, 'Google': 973, 'Phone': 303, 'Amazon Shopping': 73, 'Google Play Store': 143, 'Facebook Messenger': 75, 'Clock': 44, 'Messages': 1, 'YouTube': 86, 'Maps': 27, 'MUIQ Survey App': 4, 'Google Drive': 6, 'Google Play Music': 6, 'Pinterest': 26}
user_id:  19
app_name_to_count_dict:  {'Messages': 27, 'Facebook': 18, 'Gmail': 21, 'Pinterest': 12, 'Google Play Store': 6, 'Facebook Messenger': 19, 'YouTube': 19, 'Snapchat': 18, 'Contacts': 2, 'Amazon Shopping': 4, 'Google Chrome': 20, 'Settings': 3, 'Calculator': 1, 'Spotify Music': 1, 'Instagram': 1, 'Maps': 1, 'Netflix': 1}
user_id:  20
app_name_to_count_dict:  {'Calculator': 1, 'Gmail': 20, 'YouTube': 6, 'Camera': 2, 'Google': 6, 'Samsung Notes': 1, 'Google Chrome': 34, 'Samsung Gallery': 2, 'Google Play Store': 4, 'Settings': 4, 'Google Photos': 2}
user_id:  21
app_name_to_count_dict:  {'Contacts': 31, 'Settings': 11, 'Flipboard Briefing': 20, 'Discord': 168, 'YouTube': 124, 'Samsung Email': 174, 'Google Photos': 3, 'Google Chrome': 60, 'Gmail': 12, 'Facebook': 19, 'Google Play Store': 20, 'Samsung Notes': 5, 'Google Drive': 3, 'Camera': 8, 'Facebook Messenger': 22, 'Messages': 36, 'Maps': 10, 'Google Play Music': 3, 'Calculator': 1}
user_id:  22
app_name_to_count_dict:  {'Facebook': 129, 'Samsung Pay': 12, 'Google': 64, 'Google Chrome': 86, 'Walmart': 5, 'Pandora Music': 61, 'Google Play Store': 17, 'Contacts': 15, 'Messages': 18, 'Yahoo Mail': 55, 'Samsung Email': 55, 'Gmail': 4, 'Samsung Internet Browser': 39, 'Settings': 31, 'Maps': 3, 'Instagram': 41, 'Camera': 6, 'OfferUp': 1, 'Facebook Messenger': 66, 'Snapchat': 3, 'Lucktastic': 11, 'YouTube': 7, 'Amazon Shopping': 2, 'Spotify Music': 1, 'Calendar': 2, 'Calculator': 1, 'TextNow': 1}
user_id:  23
app_name_to_count_dict:  {'Samsung Email': 33, 'Messages': 30, 'Facebook': 30, 'Twitter': 4, 'Samsung Internet Browser': 15, 'Facebook Messenger': 2, 'Contacts': 15, 'Calendar': 2, 'Google': 13, 'Amazon Shopping': 3, 'Google Play Store': 7, 'Settings': 3, 'Google Chrome': 7, 'eBay': 6}
user_id:  24
app_name_to_count_dict:  {'Google Chrome': 31, 'YouTube': 5, 'Google': 42, 'Google Drive': 1, 'Calendar': 4, 'Google Play Store': 11, 'Settings': 2, 'Gmail': 3}
user_id:  25
app_name_to_count_dict:  {'Instagram': 45, 'Reddit': 35, 'Google': 235, 'Facebook Messenger': 193, 'Google Chrome': 493, 'Snapchat': 178, 'Gmail': 242, 'Google Photos': 24, 'eBay': 21, 'YouTube': 4, 'Messages': 152, 'Amazon Shopping': 17, 'Clock': 2, 'Spotify Music': 125, 'Twitter': 68, 'Netflix': 1, 'Google Play Store': 4, 'Settings': 85, 'Google Drive': 1, 'Phone': 4, 'Ibotta': 1, 'Walmart': 1}
user_id:  26
app_name_to_count_dict:  {'Android In Call UI': 848, 'YouTube': 57, 'Contacts': 709, 'WhatsApp Messenger': 438, 'Settings': 37, 'Google Chrome': 366, 'Maps': 10, 'Microsoft Outlook': 121, 'Gmail': 307, 'Messaging': 84, 'Google Play Store': 98, 'Facebook': 70, 'Google Photos': 7, 'Amazon Shopping': 48, 'Google': 102, 'Facebook Messenger': 16, 'Hangouts': 11}
user_id:  27
app_name_to_count_dict:  {'YouTube': 29, 'Gmail': 15, 'Google Chrome': 57, 'Google Play Store': 11, 'Google Photos': 2, 'Phone': 1, 'Settings': 1, 'Google Drive': 13, 'Discord': 4, 'Google': 1}
user_id:  28
app_name_to_count_dict:  {'Facebook': 26, 'Facebook Messenger': 16, 'Maps': 7, 'Google Chrome': 45, 'Gmail': 43, 'WhatsApp Messenger': 38, 'Settings': 9, 'Google Drive': 6, 'Google': 3, 'Google Photos': 5, 'Phone': 12, 'Clock': 1, 'Messages': 3, 'Google Play Store': 2, 'Hulu': 1}
user_id:  29
app_name_to_count_dict:  {'Google Chrome': 202, 'Facebook Messenger': 40, 'Messages': 101, 'Messenger Lite': 68, 'Gmail': 11, 'Phone': 34, 'Contacts': 14, 'Settings': 20, 'Calendar': 13, 'Google Play Store': 9, 'Instagram': 2}
user_id:  30
app_name_to_count_dict:  {'Google': 1, 'Contacts': 32, 'Samsung Gallery': 21, 'Maps': 1, 'Google Chrome': 23, 'Google Play Store': 11, 'Settings': 14, 'YouTube': 4, 'Calculator': 1, 'imo': 9, 'Messages': 11, 'Snapchat': 2, 'WhatsApp Messenger': 11, 'Camera': 6, 'Swagbucks': 1, 'Calendar': 1}
user_id:  31
app_name_to_count_dict:  {'Telegram': 1399, 'Settings': 391, 'Google Chrome': 185, 'Maps': 82, 'Google': 116, 'Clean Master': 435, 'Google Play Store': 61, 'YouTube': 822, 'Google Drive': 2, 'Gmail': 1, 'WhatsApp Messenger': 33}
user_id:  32
app_name_to_count_dict:  {'Gmail': 2, 'Google': 94, 'Facebook': 22, 'Google Chrome': 33, 'Google Play Store': 13, 'Clock': 3, 'Facebook Messenger': 3, 'Google Photos': 3, 'Settings': 1}
user_id:  33
app_name_to_count_dict:  {'Contacts': 266, 'Messaging': 292, 'Podcast Addict': 354, 'Samsung Email': 143, 'Samsung Internet Browser': 476, 'The PCH App': 6, 'Robinhood': 200, 'Android In Call UI': 359, 'YouTube': 188, 'Settings': 58, 'Google Play Store': 49, 'Maps': 89, 'Samsung Gallery': 22, 'Walmart': 6, 'Camera': 24, 'Calculator': 1, 'Google Drive': 18}
user_id:  34
app_name_to_count_dict:  {'Facebook': 4, 'Gmail': 9, 'Google Drive': 11, 'Facebook Messenger': 14, 'Google Chrome': 18, 'YouTube': 5, 'Phone': 11, 'Android In Call UI': 10, 'Google Play Store': 2, 'Settings': 1, 'Walmart': 3}
user_id:  35
app_name_to_count_dict:  {'Google Chrome': 16, 'Settings': 10, 'Gmail': 13, 'Samsung Gallery': 5, 'Camera': 3, 'Telegram': 5, 'Google Play Store': 2, 'Samsung Internet Browser': 1, 'Samsung Notes': 1}
user_id:  36
app_name_to_count_dict:  {'Google': 295, 'Discord': 40, 'YouTube': 344, 'Google Chrome': 295, 'Facebook': 102, 'Instagram': 21, 'Phone': 15, 'Maps': 75, 'Clock': 35, 'Facebook Messenger': 110, 'Google Play Store': 44, 'Settings': 49, 'Spotify Music': 24, 'Gmail': 3, 'Amazon Shopping': 3, 'Google Photos': 7, 'PayPal Mobile Cash': 1}
user_id:  37
app_name_to_count_dict:  {'Phone': 3, 'Facebook': 56, 'Clock': 98, 'Settings': 22, 'Reddit': 16, 'Gmail': 118, 'YouTube': 75, 'Google Chrome': 78, 'Google': 37, 'Facebook Messenger': 8, 'Google Play Store': 31, 'Google Photos': 28, 'Verizon Messages': 9, 'Calendar': 2, 'Walmart': 3, 'Google Play Music': 8, 'Google Drive': 3}
user_id:  38
app_name_to_count_dict:  {'Yahoo Mail': 154, 'Google Chrome': 124, 'Phone': 62, 'Hangouts': 136, 'Gmail': 122, 'Google': 150, 'Amazon Shopping': 14, 'Messages': 21, 'Facebook Messenger': 21, 'Settings': 5, 'Google Play Store': 3, 'Clock': 20, 'eBay': 1, 'Google Drive': 9}
user_id:  39
app_name_to_count_dict:  {'Facebook': 221, 'Facebook Messenger': 317, 'Google': 581, 'Gmail': 167, 'Maps': 31, 'Settings': 20, 'Google Chrome': 53, 'Quora': 18, 'Snapchat': 1, 'Google Play Store': 12, 'Phone': 23, 'Instagram': 99, 'Google Drive': 13, 'Twitter': 6, 'Amazon Shopping': 7, 'YouTube': 10, 'Google Photos': 8, 'Pandora Music': 3, 'Messages': 4}
user_id:  40
app_name_to_count_dict:  {'Facebook Messenger': 155, 'Facebook': 116, 'Twitter': 3, 'Microsoft Outlook': 40, 'Google Chrome': 41, 'Amazon Shopping': 4, 'Google Play Store': 12, 'Words With Friends 2': 7, 'Messaging': 34, 'Google': 8, 'Calorie Counter': 1, 'Android In Call UI': 58, 'Contacts': 52, 'Instagram': 10, 'Spotify Music': 24, 'Settings': 2}
user_id:  41
app_name_to_count_dict:  {'Google Chrome': 25, 'Spotify Music': 66, 'Contacts': 40, 'YouTube': 4, 'Yahoo Mail': 26, 'Samsung Gallery': 2, 'Messages': 58, 'Settings': 1, 'Calculator': 4, 'Calendar': 11, 'Facebook': 84, 'Google Play Store': 2, 'Facebook Messenger': 2, 'Samsung Internet Browser': 6, 'Camera': 1}
user_id:  42
app_name_to_count_dict:  {'Reddit': 12, 'Google': 39, 'Google Play Store': 9, 'Settings': 12, 'Google Chrome': 31, 'Messaging': 14, 'Camera': 2, 'Samsung Gallery': 1, 'Snapchat': 1, 'Maps': 1, 'Samsung Internet Browser': 4}
user_id:  43
app_name_to_count_dict:  {'Messages': 93, 'Google': 399, 'Pinterest': 19, 'Google Chrome': 493, 'Google Play Store': 44, 'Pandora Music': 74, 'Microsoft Outlook': 8, 'Settings': 7, 'Instagram': 1, 'Camera': 27, 'Snapchat': 1, 'Maps': 2, 'Facebook': 2, 'Twitter': 14, 'Samsung Gallery': 17, 'YouTube': 4}
user_id:  44
app_name_to_count_dict:  {'Google Chrome': 217, 'Google Play Store': 11, 'Settings': 36, 'Verizon Messages': 53, 'Calculator': 14, 'Calendar': 10, 'Reddit': 82, 'Gmail': 33, 'Netflix': 5, 'Instagram': 1, 'Maps': 22, 'Camera': 4, 'Samsung Gallery': 4, 'Robinhood': 10, 'YouTube': 12, 'Contacts': 12, 'Google': 5}
user_id:  45
app_name_to_count_dict:  {'Calendar': 29, 'Gmail': 40, 'Maps': 32, 'Snapchat': 16, 'Google': 12, 'Reddit': 16, 'Google Photos': 24, 'Google Play Store': 53, 'Settings': 28, 'Google Drive': 7, 'YouTube': 9, 'Discord': 4, 'Contacts': 1}
user_id:  46
app_name_to_count_dict:  {'Facebook': 25, 'WhatsApp Messenger': 203, 'Messaging': 133, 'Google Chrome': 75, 'Contacts': 218, 'Android In Call UI': 216, 'Gmail': 66, 'Google': 10, 'Flipboard Briefing': 6, 'Samsung Email': 5, 'Camera': 2, 'Facebook Messenger': 7, 'Telegram': 31, 'YouTube': 11, 'Samsung Gallery': 1, 'Twitter': 13, 'Hangouts': 1, 'Instagram': 7, 'Samsung Notes': 15, 'Settings': 24, 'Calculator': 1, 'Google Play Store': 1}
user_id:  47
app_name_to_count_dict:  {'Settings': 6, 'Contacts': 21, 'Android In Call UI': 13, 'Google Play Store': 22, 'Google Drive': 3, 'Gmail': 36, 'Messaging': 31, 'Google Chrome': 90, 'Google Photos': 6, 'Facebook Messenger': 30, 'Facebook': 11, 'Google': 3, 'YouTube': 6, 'Spotify Music': 6}
user_id:  48
app_name_to_count_dict:  {'Instagram': 24, 'Twitter': 86, 'Google Chrome': 34, 'Gmail': 3, 'Telegram': 45, 'Messaging': 17, 'WhatsApp Messenger': 14, 'Google': 2, 'YouTube': 14, 'Maps': 3, 'Contacts': 8, 'imo': 1, 'Android In Call UI': 16, 'Phone': 13, 'Google Play Store': 3, 'Settings': 1}
user_id:  49
app_name_to_count_dict:  {'Messages': 219, 'Samsung Pay': 119, 'Contacts': 42, 'Google Chrome': 16, 'Gmail': 26, 'Instagram': 29, 'Calendar': 18, 'Settings': 3, 'Google': 16, 'Samsung Internet Browser': 3, 'Facebook': 2, 'Google Play Store': 8, 'Samsung Gallery': 3, 'Spotify Music': 6, 'Calculator': 2, 'Google Drive': 1}
user_id:  50
app_name_to_count_dict:  {'Samsung Internet Browser': 1657, 'Reward Stash': 2471, 'Calculator': 33, 'Settings': 112, 'Maps': 123, 'Camera': 141, 'Samsung Gallery': 8, 'Movie Play Box': 541, 'Google Play Store': 245, 'Contacts': 21, 'Google Chrome': 251, 'YouTube': 19, 'Messaging': 7, 'Pandora Music': 63, 'Walmart': 43, 'Facebook Messenger': 27, 'Google': 56, 'Swagbucks': 64, 'Google Drive': 3, 'MUIQ Survey App': 15, 'Google Photos': 6}
user_id:  51
app_name_to_count_dict:  {'Google': 2, 'YouTube': 6, 'Maps': 1, 'Google Chrome': 16, 'Google Play Store': 7, 'Settings': 4, 'Google Play Music': 1}
user_id:  52
app_name_to_count_dict:  {'Discord': 85, 'Google Chrome': 33, 'Facebook': 17, 'Google': 35, 'Camera': 15, 'Gmail': 10, 'Facebook Messenger': 1, 'Samsung Gallery': 12, 'Twitter': 11, 'Contacts': 4, 'Google Play Store': 2, 'Settings': 6, 'YouTube': 5, 'Calendar': 5, 'Messages': 1}
user_id:  53
app_name_to_count_dict:  {'Google Play Store': 3, 'Google Chrome': 5, 'Google': 10, 'Google Photos': 1, 'Settings': 2, 'Gmail': 1}
user_id:  54
app_name_to_count_dict:  {'Facebook': 181, 'Messaging': 107, 'Google Chrome': 147, 'Contacts': 37, 'Android In Call UI': 34, 'Hangouts': 79, 'Amazon Shopping': 36, 'Walmart': 9, 'Pandora Music': 105, 'Words With Friends 2': 96, 'Twitter': 18, 'Maps': 27, 'Google': 29, 'Gmail': 102, 'YouTube': 4, 'Google Play Store': 17, 'Settings': 5, 'Facebook Messenger': 9, 'Google Drive': 1, 'Calendar': 8, 'Google Photos': 2, 'Snapchat': 1, 'Google Play Music': 4}
user_id:  55
app_name_to_count_dict:  {'Google': 2, 'Samsung Internet Browser': 66, 'Contacts': 35, 'Gmail': 15, 'Ibotta': 1, 'Microsoft Outlook': 22, 'Samsung Pay': 1, 'Messages': 34, 'Facebook': 33, 'Google Play Music': 4, 'Snapchat': 3, 'Camera': 8, 'Samsung Gallery': 14, 'Google Drive': 9, 'Google Chrome': 3, 'Facebook Messenger': 5, 'Settings': 8, 'Pinterest': 10, 'Google Play Store': 2, 'YouTube': 4, 'eBay': 4, 'PayPal Mobile Cash': 1, 'Walmart': 8, 'Maps': 2}
user_id:  56
app_name_to_count_dict:  {'Google Chrome': 34, 'Google': 22, 'Gmail': 13, 'Google Play Store': 6, 'Settings': 3, 'Maps': 3}
user_id:  57
app_name_to_count_dict:  {'Yahoo Mail': 67, 'Google': 31, 'Google Chrome': 30, 'Samsung Email': 22, 'Contacts': 14, 'Messages': 30, 'Microsoft Bing Search': 6, 'YouTube': 9, 'Google Play Store': 2, 'Maps': 11, 'Flipboard Briefing': 4, 'WhatsApp Messenger': 11, 'Settings': 2}
user_id:  58
app_name_to_count_dict:  {'S’more': 347, 'Slidejoy': 231, 'Google': 8, 'Google Chrome': 30, 'Google Play Store': 15, 'YouTube': 12, 'Facebook': 12, 'Facebook Messenger': 35, 'Reddit': 21, 'Settings': 9, 'Google Photos': 13, 'Gmail': 8, 'Google Drive': 5, 'Contacts': 1, 'Podcast Addict': 42, 'Phone': 1}
user_id:  59
app_name_to_count_dict:  {'Instagram': 68, 'Samsung Email': 230, 'Facebook': 274, 'Google Play Store': 10, 'Google': 24, 'Verizon Messages': 181, 'Samsung Pay': 180, 'Google Chrome': 287, 'Contacts': 51, 'Facebook Messenger': 53, 'Camera': 3, 'Calculator': 3, 'YouTube': 32, 'Calorie Counter': 17, 'Ibotta': 1, 'Twitter': 9, 'Settings': 1}
user_id:  60
app_name_to_count_dict:  {'Google Play Store': 45, 'Facebook': 51, 'Google Chrome': 66, 'Gmail': 27, 'Settings': 23, 'Hangouts': 20, 'Google': 35, 'Robinhood': 6, 'eBay': 99, 'YouTube': 36, 'Twitter': 3, 'Clean Master': 5, 'Receipt Hog': 1, 'Facebook Messenger': 28, 'MUIQ Survey App': 50, 'Walmart': 35, 'Contacts': 2, 'Messaging': 1, 'Google Drive': 3, 'Android In Call UI': 1}
user_id:  61

{0: 'Minesweeper Classic (Mines)',
 1: 'Google',
 2: 'Google Chrome',
 3: 'Google Chrome',
 4: 'Google Chrome',
 5: 'Twitter',
 6: 'Reddit',
 7: 'Google',
 8: 'Words With Friends 2',
 9: 'Google Chrome',
 10: 'Google Chrome',
 11: 'Samsung Internet Browser',
 12: 'WhatsApp Messenger',
 13: 'Facebook',
 14: 'Google Chrome',
 15: 'Gmail',
 16: 'Slidejoy',
 17: 'Discord',
 18: 'Google Chrome',
 19: 'Messages',
 20: 'Google Chrome',
 21: 'Samsung Email',
 22: 'Facebook',
 23: 'Samsung Email',
 24: 'Google',
 25: 'Google Chrome',
 26: 'Android In Call UI',
 27: 'Google Chrome',
 28: 'Google Chrome',
 29: 'Google Chrome',
 30: 'Contacts',
 31: 'Telegram',
 32: 'Google',
 33: 'Samsung Internet Browser',
 34: 'Google Chrome',
 35: 'Google Chrome',
 36: 'YouTube',
 37: 'Gmail',
 38: 'Yahoo Mail',
 39: 'Google',
 40: 'Facebook Messenger',
 41: 'Facebook',
 42: 'Google',
 43: 'Google Chrome',
 44: 'Google Chrome',
 45: 'Google Play Store',
 46: 'Contacts',
 47: 'Google Chrome',
 48: 'Twitter',
 49: 'Messages',
 50: 'Reward Stash',
 51: 'Google Chrome',
 52: 'Discord',
 53: 'Google',
 54: 'Facebook',
 55: 'Samsung Internet Browser',
 56: 'Google Chrome',
 57: 'Yahoo Mail',
 58: 'S’more',
 59: 'Google Chrome',
 60: 'eBay',
 61: 'SurveyCow',
 62: 'Google',
 63: 'Snapchat',
 64: 'Google Chrome',
 65: 'Hulu',
 66: 'Google Chrome',
 67: 'Facebook Messenger',
 68: 'Google Chrome',
 69: 'Messages',
 70: 'Instagram',
 71: 'Facebook Messenger',
 72: 'Messages',
 73: 'Google',
 74: 'Google Chrome',
 75: 'Google Chrome',
 76: 'Google Chrome',
 77: 'Settings',
 78: 'Android In Call UI',
 79: 'Messages',
 80: 'Contacts',
 81: 'Telegram',
 82: 'Slidejoy',
 83: 'Army Men Strike',
 84: 'WhatsApp Messenger',
 85: 'Verizon Messages',
 86: 'Google Chrome',
 87: 'Google Chrome',
 88: 'Facebook',
 89: 'Google',
 90: 'Messages',
 91: 'Reddit',
 92: 'Samsung Pay',
 93: 'Google Chrome',
 94: 'Google Chrome',
 95: 'Google Chrome',
 96: 'Facebook Messenger',
 97: 'Google',
 98: 'Facebook Messenger',
 99: 'Verizon Messages',
 100: 'Settings',
 101: 'Instagram',
 102: 'Facebook',
 103: 'Facebook',
 104: 'Google Chrome',
 105: 'Messages',
 106: 'Google Chrome',
 107: 'Samsung Internet Browser',
 108: 'Messages',
 109: 'Google Chrome',
 110: 'Google',
 111: 'Google',
 112: 'Slidejoy',
 113: 'Google Chrome',
 114: 'Samsung Email',
 115: 'Gmail',
 116: 'Facebook Messenger',
 117: 'Telegram',
 118: 'Facebook',
 119: 'Instagram',
 120: 'Facebook',
 121: 'Discord',
 122: 'Google',
 123: 'Google',
 124: 'Reddit',
 125: 'Google',
 126: 'Google Chrome',
 127: 'Gmail',
 128: 'Samsung Pay',
 129: 'Google',
 130: 'Google Chrome',
 131: 'Instagram',
 132: 'Messages',
 133: 'Google',
 134: 'Gmail',
 135: 'Google Chrome',
 136: 'Telegram',
 137: 'Google Chrome',
 138: 'Telegram X',
 139: 'Contacts',
 140: 'Google Chrome',
 141: 'Messaging',
 142: 'Facebook Messenger',
 143: 'Google',
 144: 'Google Chrome',
 145: 'Google',
 146: 'Messages',
 147: 'Faceu',
 148: 'Google Chrome',
 149: 'Google',
 150: 'Facebook Messenger',
 151: 'Messages',
 152: 'Google Chrome',
 153: 'WhatsApp Messenger',
 154: 'Messages',
 155: 'Google Chrome',
 156: 'Google Chrome',
 157: 'Settings',
 158: 'Facebook Messenger',
 159: 'Android In Call UI',
 160: 'Google Chrome',
 161: 'Facebook',
 162: 'Google Chrome',
 163: 'Instagram',
 164: 'Google Chrome',
 165: 'Google Chrome',
 166: 'Google Chrome',
 167: 'Google Chrome',
 168: 'Messages',
 169: 'Settings',
 170: 'Google',
 171: 'Settings',
 172: 'Facebook',
 173: 'Google Chrome',
 174: 'Google',
 175: 'Snapchat',
 176: 'Google Chrome',
 177: 'Settings',
 178: 'Messages',
 179: 'Facebook Messenger',
 180: 'Google Chrome',
 181: 'Google Chrome',
 182: 'YouTube',
 183: 'WhatsApp Messenger',
 184: 'Android In Call UI',
 185: 'Facebook Messenger',
 186: 'Facebook',
 187: 'Google',
 188: 'Gmail',
 189: 'Google Chrome',
 190: 'Google Chrome',
 191: 'Google Chrome',
 192: 'Google Chrome',
 193: 'Google Chrome',
 194: 'WhatsApp Messenger',
 195: 'Google Chrome',
 196: 'Telegram',
 197: 'Google Chrome',
 198: 'Slidejoy',
 199: 'Google Chrome',
 200: 'Discord',
 201: 'Reddit',
 202: 'S’more',
 203: 'Facebook Messenger',
 204: 'Verizon Messages',
 205: 'Google Chrome',
 206: 'Google Chrome',
 207: 'Messages',
 208: 'Google Chrome',
 209: 'Google Chrome',
 210: 'Google',
 211: 'Telegram',
 212: 'Reddit',
 213: 'Facebook',
 214: 'Google Chrome',
 215: 'WhatsApp Messenger',
 216: 'Verizon Messages',
 217: 'Facebook',
 218: 'Hangouts',
 219: 'Facebook',
 220: 'Google Chrome',
 221: 'Contacts',
 222: 'Google',
 223: 'Google',
 224: 'Samsung Pay',
 225: 'Gmail',
 226: 'Facebook',
 227: 'Telegram',
 228: 'Google Play Store',
 229: 'Messages',
 230: 'Google Chrome',
 231: 'Verizon Messages',
 232: 'Flipboard Briefing',
 233: 'Microsoft Outlook',
 234: 'Messages',
 235: 'YouTube',
 236: 'Google Chrome',
 237: 'Google Chrome',
 238: 'Slidejoy',
 239: 'Google Chrome',
 240: 'Telegram',
 241: 'Messages',
 242: 'Facebook',
 243: 'Google Play Store',
 244: 'WhatsApp Messenger',
 245: 'Google',
 246: 'Google Chrome',
 247: 'Telegram',
 248: 'Telegram',
 249: 'Google',
 250: 'Settings',
 251: 'Google Chrome',
 252: 'Google Chrome',
 253: 'Hangouts',
 254: 'Verizon Messages',
 255: 'Google Chrome',
 256: 'Google Chrome',
 257: 'Google',
 258: 'Google',
 259: 'Samsung Pay',
 260: 'Google',
 261: 'Google Chrome',
 262: 'Telegram',
 263: 'Google Chrome',
 264: 'Twitter',
 265: 'Google Chrome',
 266: 'Google Chrome',
 267: 'AOL',
 268: 'Settings',
 269: 'Phone',
 270: 'Google',
 271: 'Reddit',
 272: 'Settings',
 273: 'Messages',
 274: 'Samsung Pay',
 275: 'Reddit',
 276: 'Google Chrome',
 277: 'Google',
 278: 'Facebook',
 279: 'Google Chrome',
 280: 'Maps',
 281: 'Messages',
 282: 'Google',
 283: 'Google Chrome',
 284: 'Facebook',
 285: 'Google',
 286: 'Gmail',
 287: 'Facebook',
 288: 'Settings',
 289: 'S’more',
 290: 'Google',
 291: 'Facebook'}

In [49]:
# iterate through all df_start interactions and choose app_name as most popular app for user_id
df_start['most_popular_app_name'] = df_start.apply(lambda row: user_to_most_popular_app_dict[row['user_id']], axis=1)

# create dicitonary user to accuracy
user_to_accuracy_dict = {}

# go through all interactions and check if app_name is in random_app_name for each user and save accuracy
for user_id, user_df in df_user:
    # iterate through all interactions for user_id
    accuracy = 0

    for index, row in user_df.iterrows():
        if row['app_name'] == row['most_popular_app_name']:
            accuracy += 1

    user_to_accuracy_dict[user_id] = accuracy / len(user_df)

# print user to accuracy dictionary
user_to_accuracy_dict

C:\Users\Brin\AppData\Local\Temp\ipykernel_17340\596777393.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_start['most_popular_app_name'] = df_start.apply(lambda row: user_to_most_popular_app_dict[row['user_id']], axis=1)

{0: 0.22053231939163498,
 1: 0.19004524886877827,
 2: 0.3173913043478261,
 3: 0.40236686390532544,
 4: 0.26973684210526316,
 5: 0.3367299133286484,
 6: 0.24717595251771013,
 7: 0.23479087452471484,
 8: 0.36666666666666664,
 9: 0.31689497716894977,
 10: 0.42105263157894735,
 11: 0.3344778254649499,
 12: 0.15019762845849802,
 13: 0.24373259052924792,
 14: 0.48936170212765956,
 15: 0.18733850129198967,
 16: 0.32971014492753625,
 17: 0.29012345679012347,
 18: 0.2516215611719973,
 19: 0.15517241379310345,
 20: 0.4146341463414634,
 21: 0.23835616438356164,
 22: 0.17527173913043478,
 23: 0.19411764705882353,
 24: 0.42424242424242425,
 25: 0.2553081305023304,
 26: 0.2547311504956443,
 27: 0.4253731343283582,
 28: 0.2073732718894009,
 29: 0.39299610894941633,
 30: 0.21476510067114093,
 31: 0.3966543804933371,
 32: 0.5402298850574713,
 33: 0.18659349274794199,
 34: 0.20454545454545456,
 35: 0.2857142857142857,
 36: 0.23513328776486672,
 37: 0.19831932773109243,
 38: 0.1828978622327791,
 39: 0.3644918444165621,
 40: 0.27336860670194,
 41: 0.25301204819277107,
 42: 0.30952380952380953,
 43: 0.4091286307053942,
 44: 0.4086629001883239,
 45: 0.19557195571955718,
 46: 0.20354808590102708,
 47: 0.31690140845070425,
 48: 0.3028169014084507,
 49: 0.4269005847953216,
 50: 0.41838807991872673,
 51: 0.43243243243243246,
 52: 0.3512396694214876,
 53: 0.45454545454545453,
 54: 0.17107750472589792,
 55: 0.22448979591836735,
 56: 0.41975308641975306,
 57: 0.2803347280334728,
 58: 0.43924050632911393,
 59: 0.20154494382022473,
 60: 0.18435754189944134,
 61: 0.25442029963557833,
 62: 0.4889867841409692,
 63: 0.1834862385321101,
 64: 0.2196969696969697,
 65: 0.75,
 66: 0.21348314606741572,
 67: 0.21459620224204987,
 68: 0.29087828297091217,
 69: 0.23788546255506607,
 70: 0.2277992277992278,
 71: 0.2877716679759099,
 72: 0.19047619047619047,
 73: 0.4835466179159049,
 74: 0.3019922254616132,
 75: 0.30684931506849317,
 76: 0.5365853658536586,
 77: 0.34306569343065696,
 78: 0.23952095808383234,
 79: 0.2923845193508115,
 80: 0.2846441947565543,
 81: 0.4690265486725664,
 82: 0.5618729096989966,
 83: 0.3450087565674256,
 84: 0.17064846416382254,
 85: 0.3235294117647059,
 86: 0.2962962962962963,
 87: 0.21836228287841192,
 88: 0.35714285714285715,
 89: 0.4262295081967213,
 90: 0.272,
 91: 0.2515151515151515,
 92: 0.2222222222222222,
 93: 0.2806201550387597,
 94: 0.19667590027700832,
 95: 0.45454545454545453,
 96: 0.2318840579710145,
 97: 0.5151515151515151,
 98: 0.5,
 99: 0.2496493688639551,
 100: 0.42857142857142855,
 101: 0.24074074074074073,
 102: 0.1896766169154229,
 103: 0.20833333333333334,
 104: 0.3106283029947152,
 105: 0.3508771929824561,
 106: 0.3258306538049303,
 107: 0.3037716615698267,
 108: 0.21561740070251284,
 109: 0.28434504792332266,
 110: 0.6382978723404256,
 111: 0.49791376912378305,
 112: 0.30028222555005185,
 113: 0.3611111111111111,
 114: 0.24398625429553264,
 115: 0.2279630732578916,
 116: 0.26238720911825236,
 117: 0.5238095238095238,
 118: 0.22012578616352202,
 119: 0.24393279402613566,
 120: 0.21875,
 121: 0.308868501529052,
 122: 0.48255813953488375,
 123: 0.6111111111111112,
 124: 0.23529411764705882,
 125: 0.2752752752752753,
 126: 0.20714285714285716,
 127: 0.28937007874015747,
 128: 0.20279206465833946,
 129: 0.3668869024485037,
 130: 0.26744186046511625,
 131: 0.25987006496751625,
 132: 0.36363636363636365,
 133: 0.4202140309155767,
 134: 0.4166666666666667,
 135: 0.29760923330585326,
 136: 0.33007676203768316,
 137: 0.23938482113005682,
 138: 0.20226775152762802,
 139: 0.16618015012510426,
 140: 0.16097560975609757,
 141: 0.5256410256410257,
 142: 0.26277372262773724,
 143: 0.3553113553113553,
 144: 0.22388059701492538,
 145: 0.1873015873015873,
 146: 0.13261648745519714,
 147: 0.2711184521000472,
 148: 0.2928813559322034,
 149: 0.3177570093457944,
 150: 0.4619758351101635,
 151: 0.21109947643979057,
 152: 0.33076923076923076,
 153: 0.2131979695431472,
 154: 0.24504436473475552,
 155: 0.2562814070351759,
 156: 0.23387096774193547,
 157: 0.375,
 158: 0.20276497695852536,
 159: 0.17204301075268819,
 160: 0.221379833206975,
 161: 0.2956777996070727,
 162: 0.24162679425837322,
 163: 0.13857677902621723,
 164: 0.2942477876106195,
 165: 0.45379746835443036,
 166: 0.8955223880597015,
 167: 0.5116279069767442,
 168: 0.2179930795847751,
 169: 0.6858108108108109,
 170: 0.65,
 171: 1.0,
 172: 0.2963917525773196,
 173: 0.2106951871657754,
 174: 0.21794871794871795,
 175: 0.16666666666666666,
 176: 0.2301255230125523,
 177: 1.0,
 178: 0.22358722358722358,
 179: 0.24678217821782178,
 180: 0.25949367088607594,
 181: 0.31,
 182: 0.31496062992125984,
 183: 0.1746641074856046,
 184: 0.3064516129032258,
 185: 0.16417910447761194,
 186: 0.25957446808510637,
 187: 0.3446858485026424,
 188: 0.22170900692840648,
 189: 0.34139784946236557,
 190: 0.48936170212765956,
 191: 0.2261904761904762,
 192: 0.25132399275993833,
 193: 0.37662337662337664,
 194: 0.41007194244604317,
 195: 0.3591549295774648,
 196: 0.3543550690147549,
 197: 0.22362869198312235,
 198: 0.5189167662285942,
 199: 0.5263157894736842,
 200: 0.34972677595628415,
 201: 0.19523809523809524,
 202: 0.5241157556270096,
 203: 0.33630620587142324,
 204: 0.1464189048511347,
 205: 0.21254612546125462,
 206: 0.2669432918395574,
 207: 0.20190023752969122,
 208: 0.31382978723404253,
 209: 0.16778523489932887,
 210: 0.46774193548387094,
 211: 0.28858218318695106,
 212: 0.2841993637327678,
 213: 0.33157894736842103,
 214: 0.17757009345794392,
 215: 0.2169249106078665,
 216: 0.3904109589041096,
 217: 0.20086083213773315,
 218: 0.4765625,
 219: 0.2942008486562942,
 220: 0.4057971014492754,
 221: 0.39145473041709056,
 222: 0.6859504132231405,
 223: 0.5,
 224: 0.30256410256410254,
 225: 0.15085158150851583,
 226: 0.2924457741211668,
 227: 0.38734706057893165,
 228: 0.45454545454545453,
 229: 0.3275229357798165,
 230: 0.2857142857142857,
 231: 0.4772929652715939,
 232: 1.0,
 233: 0.1574074074074074,
 234: 0.3333333333333333,
 235: 0.26136363636363635,
 236: 0.4444444444444444,
 237: 0.2671814671814672,
 238: 0.2755775577557756,
 239: 0.18936170212765957,
 240: 0.4658008658008658,
 241: 0.17607223476297967,
 242: 0.21948608137044967,
 243: 1.0,
 244: 0.30711920529801323,
 245: 0.21830985915492956,
 246: 0.27802690582959644,
 247: 0.24923702950152593,
 248: 0.327930174563591,
 249: 0.38724373576309795,
 250: 1.0,
 251: 0.3356539035305818,
 252: 0.24824986537425955,
 253: 0.2248062015503876,
 254: 0.20130799100756183,
 255: 0.3237283888749687,
 256: 0.42424242424242425,
 257: 0.2468944099378882,
 258: 0.39278752436647174,
 259: 0.2897172236503856,
 260: 0.43126815101645694,
 261: 0.27058823529411763,
 262: 0.33613074204946997,
 263: 0.18647406434668418,
 264: 0.2507654623392529,
 265: 0.19305555555555556,
 266: 0.24371859296482412,
 267: 0.21816742877242348,
 268: 0.767175572519084,
 269: 0.31103952084940334,
 270: 0.44827227671299347,
 271: 0.15880503144654087,
 272: 0.41379310344827586,
 273: 0.3080319596299411,
 274: 0.21929824561403508,
 275: 0.2484526967285588,
 276: 0.19951923076923078,
 277: 0.2554112554112554,
 278: 0.2925170068027211,
 279: 0.255050505050505,
 280: 0.19797979797979798,
 281: 0.25389755011135856,
 282: 0.4939271255060729,
 283: 0.34989043097151207,
 284: 0.22376093294460642,
 285: 0.3978413654618474,
 286: 0.2777777777777778,
 287: 0.2773972602739726,
 288: 1.0,
 289: 0.4019672131147541,
 290: 0.3954413216964262,
 291: 0.29411764705882354}

In [50]:
# Calculate mean and standard deviation of accuracy
mean_accuracy = np.mean(list(user_to_accuracy_dict.values()))
std_accuracy = np.std(list(user_to_accuracy_dict.values()))

mean_accuracy, std_accuracy

(0.3247922031056106, 0.15336049330744814)

### Most recently used